---
restic_rest_server_version: "0.9.7"
sha256_sum: "390b3a396f1c3ad67f9cd8ed6ae2d3c10f7c7e3a8213046009d3a905e1ee7da6"
repository_path: "/data/backup_repos/restic-rest"
repository_password: "secret_password"
repository_password_filepath: "/root/restic-rest.pwd"